download_images:
	# Link to /Nextcloud/Shared/2020/2020-02-01 RMURV2 shared with students/2020-02-11SelectedImages.zip
	wget https://nextcloud.sdu.dk/index.php/s/zMtZWaXH66Stz26/download
	unzip download
	rm download

