generate_data:
	pipenv run python aruco_board_generator.py

download_videos:
	# Link to /Nextcloud/Shared/2020020-02-01 RMURV2/2020-04-16 Fiducial markers.zip
	wget https://nextcloud.sdu.dk/index.php/s/RoknSpz6Qb973d8/download
	unzip download
	rm download

